---
deployment:
  tasks:
    # Dossier racine du sous-domaine minafroqueen.mbth3911.odns.fr (vérifier dans cPanel > Sous-domaines > Racine du document)
    - export DEPLOYPATH=/home/mbth3911/minafroqueen.mbth3911.odns.fr/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.php install.php .htaccess app assets $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/uploads $DEPLOYPATH/storage
    - /bin/cp uploads/.htaccess $DEPLOYPATH/uploads/.htaccess
    - /bin/cp storage/.htaccess $DEPLOYPATH/storage/.htaccess
